### PR TITLE
Update for php8 errors when passing null as parameter

### LINKED ISSUE #157: Issue with update Wordpress 6.5.5
Hi, the plugin doesn´t show colors since the last update of Wordpress... Could you solve it and fix it? It was ok before the update.  Thanks a lot,
I have this message too: Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in .../public_html/wp-content/plugins/the-events-calendar-category-colors/src/Category_Colors/Main.php on line 260

### PR DESCRIPTION
**Pull request by afragen**
This should fix #156 and hopefully fix #157.

Replaces #158 by starting from a different branch on my end. Sorry.

### CODE REVIEW

**Comment by afragen** [comment]
Keeping the GitHub Plugin URI to `afragen/the-events-calendar-category-colors` allows for updating of test branches via Git Updater while the `master` branch will always update from dot org.

**Review by Camwyn — COMMENTED** [review]
@afragen This makes sense, but would it make additional/more sense to trim out the empty values before the return in `Admin.php`?

i.e. array_filter( $input )

as a bonus, it would/may remove the need for all the `empty()` checks

**Comment by afragen** [comment]
@Camwyn I didn't test that just converted from null checks. Seems like a good idea.

**Comment by bordoni** [comment]
I will merge as is since it fixes the problem reported and ship as version 7.3.1 tomorrow AM  is that ok?

**Comment by afragen** [comment]
Sounds great. Checking the `array_filter` to remove empty values might actually cause issues if the code expects something to be present even if empty.

**Comment by bordoni** [comment]
@afragen it should be ready for release, I did all the version bumps on `develop` can you double check? (same to you @Camwyn)

I am out for a bit this morning, lets ship around 12 EST

**Comment by afragen** [comment]
It all looks good. 

You will need to change the Settings > Secrets > Actions for the GitHub Actions to work. This includes the deploy action to SVN.

**Pull request merged**
