### PR TITLE
Fix issue with hidden categories in 7.3.1

### PR DESCRIPTION
**Pull request by afragen**
There are 2 forum posts that seem to be related to hidden categories and v7.3.1

https://wordpress.org/support/topic/version7-3-1-upgrade-problem/
https://wordpress.org/support/topic/hidden-categories-displaying-7-3-1-update/

### CODE REVIEW

**Comment by bordoni** [comment]
Thank you so much @afragen, @andrasguseo do you mind running dev-QA on this?

**Review by bordoni — APPROVED** [review]

**Comment by afragen** [comment]
I did have confirmation of this fixing the issue from at least one user.

**Comment by bordoni** [comment]
Cool, I know you've been working with one customer trying to look at this issue, do you want me to ship anyways tomorrow AM?

**Comment by afragen** [comment]
I would say ship it. I think the outstanding forum issue has several issues. Example, they have some JS error and that code wasn't touched.

**Comment by afragen** [comment]
It's time to merge and release.

**Comment by TRILOS** [comment]
After updating TEC to v7, I witnessed this problem, too.
Now I see that https://wordpress.org/support/topic-tag/the-events-calendar-category-colors has vanished and there´s something about a fork with https://github.com/afragen/the-events-calendar-category-colors which irritates me... so how do I get the bug fix now?

**Comment by afragen** [comment]
You should try https://wordpress.org/support/plugin/the-events-calendar-category-colors/

**Comment by TRILOS** [comment]
Update v.7.3.2 of https://de.wordpress.org/plugins/the-events-calendar-category-colors/ obviously solves the problem now. Thanks to all for engaging.

**Pull request merged**
